[google]
type = "service_account"
project_id = "malnocare-459318"
private_key_id = "abc123..."
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASC...
... rest of your private key here ...
-----END PRIVATE KEY-----"""
client_email = "malnocare@malnocare-459318.iam.gserviceaccount.com"
client_id = "101655846268532504883"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/malnocare%40malnocare-459318.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
